[shell]
program               = "/usr/bin/bash"
# args                  = [ "--login", ]

#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
#TERM                  = "xterm-256color"

[window]
#dimensions            = { columns = 0, lines = 0 }
position              = { x = 0, y = 0 }
padding               = { x = 10, y = 10 }
#dynamic_padding       = true
decorations           = "None"
opacity               = 1.0
#blur                  = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"

[scrolling]
history               = 1000
#multiplier            = 3

[font]
# normal                = { family = "Hack", style = "Regular" }
# bold                  = { family = "Hack", style = "Bold" }
# italic                = { family = "Hack", style = "Italic" }
# bold_italic           = { family = "Hack", style = "Bold Italic" }
normal.family = "FiraCode Nerd Font SemBd"
size                  = 9
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[colors.primary]
background            = "#000000"
foreground            = "#FFFFFF"
# dim_foreground        = "#CDD6F4"
# bright_foreground     = "#CDD6F4"

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Block"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

