[general]
import = [
    "~/.config/alacritty/colorshemes/vesper.toml"
]
[terminal]
shell               = "/usr/bin/bash"
# args                  = [ "--login", ]

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "On"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

#[[keyboard.bindings]]
#chars = "\u0017"
#key = "Back"
#mods = "Control"


[scrolling]
history = 10000
multiplier = 3

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true
opacity               = 1.0
blur                  = false

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "U", mods = "Control|Shift", action = "ScrollPageUp" },
  { key = "D", mods = "Control|Shift", action = "ScrollPageDown" },
]

